# Generated by Django 4.1.13 on 2023-11-26 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('user_UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'balance',
                'verbose_name_plural': 'balances',
            },
        ),
    ]
