# Generated by Django 4.1.13 on 2023-11-26 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operations_history',
            fields=[
                ('operation_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_UUID', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'operations_history',
                'verbose_name_plural': 'operations_histories',
            },
        ),
    ]
